/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as LogInRouteImport } from './routes/log-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherSettingsRouteImport } from './routes/teacher/settings'
import { Route as TeacherCalendarRouteImport } from './routes/teacher/calendar'
import { Route as StudentSettingsRouteImport } from './routes/student/settings'
import { Route as StudentNotificationsRouteImport } from './routes/student/notifications'
import { Route as StudentCoursesRouteImport } from './routes/student/courses'
import { Route as StudentCalendarRouteImport } from './routes/student/calendar'
import { Route as OwnerSettingsRouteImport } from './routes/owner/settings'
import { Route as OwnerPaymentsRouteImport } from './routes/owner/payments'
import { Route as OwnerDashboardRouteImport } from './routes/owner/dashboard'
import { Route as OwnerAnnouncementsRouteImport } from './routes/owner/announcements'
import { Route as TeacherNotificationsIndexRouteImport } from './routes/teacher/notifications.index'
import { Route as TeacherClassesIndexRouteImport } from './routes/teacher/classes/index'
import { Route as OwnerTeachersIndexRouteImport } from './routes/owner/teachers.index'
import { Route as OwnerStudentsIndexRouteImport } from './routes/owner/students.index'
import { Route as TeacherNotificationsAddRouteImport } from './routes/teacher/notifications.add'
import { Route as TeacherClassesAllCollectionsRouteImport } from './routes/teacher/classes/allCollections'
import { Route as TeacherClassesFolderIdRouteImport } from './routes/teacher/classes/$folderId'
import { Route as OwnerTeachersAddRouteImport } from './routes/owner/teachers.add'
import { Route as OwnerStudentsAddRouteImport } from './routes/owner/students.add'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const LogInRoute = LogInRouteImport.update({
  id: '/log-in',
  path: '/log-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSettingsRoute = TeacherSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherCalendarRoute = TeacherCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentSettingsRoute = StudentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCalendarRoute = StudentCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => StudentRoute,
} as any)
const OwnerSettingsRoute = OwnerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPaymentsRoute = OwnerPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAnnouncementsRoute = OwnerAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => OwnerRoute,
} as any)
const TeacherNotificationsIndexRoute =
  TeacherNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => TeacherRoute,
  } as any)
const TeacherClassesIndexRoute = TeacherClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => TeacherRoute,
} as any)
const OwnerTeachersIndexRoute = OwnerTeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerStudentsIndexRoute = OwnerStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => OwnerRoute,
} as any)
const TeacherNotificationsAddRoute = TeacherNotificationsAddRouteImport.update({
  id: '/notifications/add',
  path: '/notifications/add',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherClassesAllCollectionsRoute =
  TeacherClassesAllCollectionsRouteImport.update({
    id: '/classes/allCollections',
    path: '/classes/allCollections',
    getParentRoute: () => TeacherRoute,
  } as any)
const TeacherClassesFolderIdRoute = TeacherClassesFolderIdRouteImport.update({
  id: '/classes/$folderId',
  path: '/classes/$folderId',
  getParentRoute: () => TeacherRoute,
} as any)
const OwnerTeachersAddRoute = OwnerTeachersAddRouteImport.update({
  id: '/teachers/add',
  path: '/teachers/add',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerStudentsAddRoute = OwnerStudentsAddRouteImport.update({
  id: '/students/add',
  path: '/students/add',
  getParentRoute: () => OwnerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/log-in': typeof LogInRoute
  '/owner': typeof OwnerRouteWithChildren
  '/sign-up': typeof SignUpRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/owner/announcements': typeof OwnerAnnouncementsRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/payments': typeof OwnerPaymentsRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/settings': typeof StudentSettingsRoute
  '/teacher/calendar': typeof TeacherCalendarRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/owner/students/add': typeof OwnerStudentsAddRoute
  '/owner/teachers/add': typeof OwnerTeachersAddRoute
  '/teacher/classes/$folderId': typeof TeacherClassesFolderIdRoute
  '/teacher/classes/allCollections': typeof TeacherClassesAllCollectionsRoute
  '/teacher/notifications/add': typeof TeacherNotificationsAddRoute
  '/owner/students': typeof OwnerStudentsIndexRoute
  '/owner/teachers': typeof OwnerTeachersIndexRoute
  '/teacher/classes': typeof TeacherClassesIndexRoute
  '/teacher/notifications': typeof TeacherNotificationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/log-in': typeof LogInRoute
  '/owner': typeof OwnerRouteWithChildren
  '/sign-up': typeof SignUpRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/owner/announcements': typeof OwnerAnnouncementsRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/payments': typeof OwnerPaymentsRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/settings': typeof StudentSettingsRoute
  '/teacher/calendar': typeof TeacherCalendarRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/owner/students/add': typeof OwnerStudentsAddRoute
  '/owner/teachers/add': typeof OwnerTeachersAddRoute
  '/teacher/classes/$folderId': typeof TeacherClassesFolderIdRoute
  '/teacher/classes/allCollections': typeof TeacherClassesAllCollectionsRoute
  '/teacher/notifications/add': typeof TeacherNotificationsAddRoute
  '/owner/students': typeof OwnerStudentsIndexRoute
  '/owner/teachers': typeof OwnerTeachersIndexRoute
  '/teacher/classes': typeof TeacherClassesIndexRoute
  '/teacher/notifications': typeof TeacherNotificationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/log-in': typeof LogInRoute
  '/owner': typeof OwnerRouteWithChildren
  '/sign-up': typeof SignUpRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/owner/announcements': typeof OwnerAnnouncementsRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/payments': typeof OwnerPaymentsRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/settings': typeof StudentSettingsRoute
  '/teacher/calendar': typeof TeacherCalendarRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/owner/students/add': typeof OwnerStudentsAddRoute
  '/owner/teachers/add': typeof OwnerTeachersAddRoute
  '/teacher/classes/$folderId': typeof TeacherClassesFolderIdRoute
  '/teacher/classes/allCollections': typeof TeacherClassesAllCollectionsRoute
  '/teacher/notifications/add': typeof TeacherNotificationsAddRoute
  '/owner/students/': typeof OwnerStudentsIndexRoute
  '/owner/teachers/': typeof OwnerTeachersIndexRoute
  '/teacher/classes/': typeof TeacherClassesIndexRoute
  '/teacher/notifications/': typeof TeacherNotificationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/log-in'
    | '/owner'
    | '/sign-up'
    | '/student'
    | '/teacher'
    | '/owner/announcements'
    | '/owner/dashboard'
    | '/owner/payments'
    | '/owner/settings'
    | '/student/calendar'
    | '/student/courses'
    | '/student/notifications'
    | '/student/settings'
    | '/teacher/calendar'
    | '/teacher/settings'
    | '/owner/students/add'
    | '/owner/teachers/add'
    | '/teacher/classes/$folderId'
    | '/teacher/classes/allCollections'
    | '/teacher/notifications/add'
    | '/owner/students'
    | '/owner/teachers'
    | '/teacher/classes'
    | '/teacher/notifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/log-in'
    | '/owner'
    | '/sign-up'
    | '/student'
    | '/teacher'
    | '/owner/announcements'
    | '/owner/dashboard'
    | '/owner/payments'
    | '/owner/settings'
    | '/student/calendar'
    | '/student/courses'
    | '/student/notifications'
    | '/student/settings'
    | '/teacher/calendar'
    | '/teacher/settings'
    | '/owner/students/add'
    | '/owner/teachers/add'
    | '/teacher/classes/$folderId'
    | '/teacher/classes/allCollections'
    | '/teacher/notifications/add'
    | '/owner/students'
    | '/owner/teachers'
    | '/teacher/classes'
    | '/teacher/notifications'
  id:
    | '__root__'
    | '/'
    | '/log-in'
    | '/owner'
    | '/sign-up'
    | '/student'
    | '/teacher'
    | '/owner/announcements'
    | '/owner/dashboard'
    | '/owner/payments'
    | '/owner/settings'
    | '/student/calendar'
    | '/student/courses'
    | '/student/notifications'
    | '/student/settings'
    | '/teacher/calendar'
    | '/teacher/settings'
    | '/owner/students/add'
    | '/owner/teachers/add'
    | '/teacher/classes/$folderId'
    | '/teacher/classes/allCollections'
    | '/teacher/notifications/add'
    | '/owner/students/'
    | '/owner/teachers/'
    | '/teacher/classes/'
    | '/teacher/notifications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogInRoute: typeof LogInRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  SignUpRoute: typeof SignUpRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-in': {
      id: '/log-in'
      path: '/log-in'
      fullPath: '/log-in'
      preLoaderRoute: typeof LogInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/settings': {
      id: '/teacher/settings'
      path: '/settings'
      fullPath: '/teacher/settings'
      preLoaderRoute: typeof TeacherSettingsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/calendar': {
      id: '/teacher/calendar'
      path: '/calendar'
      fullPath: '/teacher/calendar'
      preLoaderRoute: typeof TeacherCalendarRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/settings': {
      id: '/student/settings'
      path: '/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof StudentSettingsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/calendar': {
      id: '/student/calendar'
      path: '/calendar'
      fullPath: '/student/calendar'
      preLoaderRoute: typeof StudentCalendarRouteImport
      parentRoute: typeof StudentRoute
    }
    '/owner/settings': {
      id: '/owner/settings'
      path: '/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof OwnerSettingsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/payments': {
      id: '/owner/payments'
      path: '/payments'
      fullPath: '/owner/payments'
      preLoaderRoute: typeof OwnerPaymentsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/dashboard': {
      id: '/owner/dashboard'
      path: '/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/announcements': {
      id: '/owner/announcements'
      path: '/announcements'
      fullPath: '/owner/announcements'
      preLoaderRoute: typeof OwnerAnnouncementsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/teacher/notifications/': {
      id: '/teacher/notifications/'
      path: '/notifications'
      fullPath: '/teacher/notifications'
      preLoaderRoute: typeof TeacherNotificationsIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/classes/': {
      id: '/teacher/classes/'
      path: '/classes'
      fullPath: '/teacher/classes'
      preLoaderRoute: typeof TeacherClassesIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/owner/teachers/': {
      id: '/owner/teachers/'
      path: '/teachers'
      fullPath: '/owner/teachers'
      preLoaderRoute: typeof OwnerTeachersIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/students/': {
      id: '/owner/students/'
      path: '/students'
      fullPath: '/owner/students'
      preLoaderRoute: typeof OwnerStudentsIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/teacher/notifications/add': {
      id: '/teacher/notifications/add'
      path: '/notifications/add'
      fullPath: '/teacher/notifications/add'
      preLoaderRoute: typeof TeacherNotificationsAddRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/classes/allCollections': {
      id: '/teacher/classes/allCollections'
      path: '/classes/allCollections'
      fullPath: '/teacher/classes/allCollections'
      preLoaderRoute: typeof TeacherClassesAllCollectionsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/classes/$folderId': {
      id: '/teacher/classes/$folderId'
      path: '/classes/$folderId'
      fullPath: '/teacher/classes/$folderId'
      preLoaderRoute: typeof TeacherClassesFolderIdRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/owner/teachers/add': {
      id: '/owner/teachers/add'
      path: '/teachers/add'
      fullPath: '/owner/teachers/add'
      preLoaderRoute: typeof OwnerTeachersAddRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/students/add': {
      id: '/owner/students/add'
      path: '/students/add'
      fullPath: '/owner/students/add'
      preLoaderRoute: typeof OwnerStudentsAddRouteImport
      parentRoute: typeof OwnerRoute
    }
  }
}

interface OwnerRouteChildren {
  OwnerAnnouncementsRoute: typeof OwnerAnnouncementsRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  OwnerPaymentsRoute: typeof OwnerPaymentsRoute
  OwnerSettingsRoute: typeof OwnerSettingsRoute
  OwnerStudentsAddRoute: typeof OwnerStudentsAddRoute
  OwnerTeachersAddRoute: typeof OwnerTeachersAddRoute
  OwnerStudentsIndexRoute: typeof OwnerStudentsIndexRoute
  OwnerTeachersIndexRoute: typeof OwnerTeachersIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerAnnouncementsRoute: OwnerAnnouncementsRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
  OwnerPaymentsRoute: OwnerPaymentsRoute,
  OwnerSettingsRoute: OwnerSettingsRoute,
  OwnerStudentsAddRoute: OwnerStudentsAddRoute,
  OwnerTeachersAddRoute: OwnerTeachersAddRoute,
  OwnerStudentsIndexRoute: OwnerStudentsIndexRoute,
  OwnerTeachersIndexRoute: OwnerTeachersIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

interface StudentRouteChildren {
  StudentCalendarRoute: typeof StudentCalendarRoute
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentSettingsRoute: typeof StudentSettingsRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCalendarRoute: StudentCalendarRoute,
  StudentCoursesRoute: StudentCoursesRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentSettingsRoute: StudentSettingsRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherCalendarRoute: typeof TeacherCalendarRoute
  TeacherSettingsRoute: typeof TeacherSettingsRoute
  TeacherClassesFolderIdRoute: typeof TeacherClassesFolderIdRoute
  TeacherClassesAllCollectionsRoute: typeof TeacherClassesAllCollectionsRoute
  TeacherNotificationsAddRoute: typeof TeacherNotificationsAddRoute
  TeacherClassesIndexRoute: typeof TeacherClassesIndexRoute
  TeacherNotificationsIndexRoute: typeof TeacherNotificationsIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherCalendarRoute: TeacherCalendarRoute,
  TeacherSettingsRoute: TeacherSettingsRoute,
  TeacherClassesFolderIdRoute: TeacherClassesFolderIdRoute,
  TeacherClassesAllCollectionsRoute: TeacherClassesAllCollectionsRoute,
  TeacherNotificationsAddRoute: TeacherNotificationsAddRoute,
  TeacherClassesIndexRoute: TeacherClassesIndexRoute,
  TeacherNotificationsIndexRoute: TeacherNotificationsIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogInRoute: LogInRoute,
  OwnerRoute: OwnerRouteWithChildren,
  SignUpRoute: SignUpRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
