/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as LogInRouteImport } from './routes/log-in'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherSettingsRouteImport } from './routes/teacher/settings'
import { Route as TeacherCalendarRouteImport } from './routes/teacher/calendar'
import { Route as StudentSettingsRouteImport } from './routes/student/settings'
import { Route as StudentCoursesRouteImport } from './routes/student/courses'
import { Route as StudentCalendarRouteImport } from './routes/student/calendar'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCalendarRouteImport } from './routes/admin/calendar'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'
import { Route as TeacherNotificationsIndexRouteImport } from './routes/teacher/notifications/index'
import { Route as TeacherClassesIndexRouteImport } from './routes/teacher/classes/index'
import { Route as StudentNotificationIndexRouteImport } from './routes/student/notification/index'
import { Route as AdminTeachersIndexRouteImport } from './routes/admin/teachers.index'
import { Route as AdminStudentsIndexRouteImport } from './routes/admin/students.index'
import { Route as TeacherNotificationsAddRouteImport } from './routes/teacher/notifications/add'
import { Route as TeacherNotificationsNotificationIdRouteImport } from './routes/teacher/notifications/$notificationId'
import { Route as TeacherClassesAllCollectionsRouteImport } from './routes/teacher/classes/allCollections'
import { Route as TeacherClassesFolderIdRouteImport } from './routes/teacher/classes/$folderId'
import { Route as StudentNotificationNotificationIdRouteImport } from './routes/student/notification/$notificationId'
import { Route as AdminTeachersAddRouteImport } from './routes/admin/teachers.add'
import { Route as AdminTeachersTeacherIdRouteImport } from './routes/admin/teachers.$teacherId'
import { Route as AdminStudentsAddRouteImport } from './routes/admin/students.add'
import { Route as AdminStudentsStudentIdRouteImport } from './routes/admin/students.$studentId'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const LogInRoute = LogInRouteImport.update({
  id: '/log-in',
  path: '/log-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSettingsRoute = TeacherSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherCalendarRoute = TeacherCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentSettingsRoute = StudentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCalendarRoute = StudentCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => StudentRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherNotificationsIndexRoute =
  TeacherNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => TeacherRoute,
  } as any)
const TeacherClassesIndexRoute = TeacherClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentNotificationIndexRoute =
  StudentNotificationIndexRouteImport.update({
    id: '/notification/',
    path: '/notification/',
    getParentRoute: () => StudentRoute,
  } as any)
const AdminTeachersIndexRoute = AdminTeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsIndexRoute = AdminStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherNotificationsAddRoute = TeacherNotificationsAddRouteImport.update({
  id: '/notifications/add',
  path: '/notifications/add',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherNotificationsNotificationIdRoute =
  TeacherNotificationsNotificationIdRouteImport.update({
    id: '/notifications/$notificationId',
    path: '/notifications/$notificationId',
    getParentRoute: () => TeacherRoute,
  } as any)
const TeacherClassesAllCollectionsRoute =
  TeacherClassesAllCollectionsRouteImport.update({
    id: '/classes/allCollections',
    path: '/classes/allCollections',
    getParentRoute: () => TeacherRoute,
  } as any)
const TeacherClassesFolderIdRoute = TeacherClassesFolderIdRouteImport.update({
  id: '/classes/$folderId',
  path: '/classes/$folderId',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentNotificationNotificationIdRoute =
  StudentNotificationNotificationIdRouteImport.update({
    id: '/notification/$notificationId',
    path: '/notification/$notificationId',
    getParentRoute: () => StudentRoute,
  } as any)
const AdminTeachersAddRoute = AdminTeachersAddRouteImport.update({
  id: '/teachers/add',
  path: '/teachers/add',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachersTeacherIdRoute = AdminTeachersTeacherIdRouteImport.update({
  id: '/teachers/$teacherId',
  path: '/teachers/$teacherId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsAddRoute = AdminStudentsAddRouteImport.update({
  id: '/students/add',
  path: '/students/add',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsStudentIdRoute = AdminStudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/log-in': typeof LogInRoute
  '/sign-up': typeof SignUpRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/settings': typeof StudentSettingsRoute
  '/teacher/calendar': typeof TeacherCalendarRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/admin/students/$studentId': typeof AdminStudentsStudentIdRoute
  '/admin/students/add': typeof AdminStudentsAddRoute
  '/admin/teachers/$teacherId': typeof AdminTeachersTeacherIdRoute
  '/admin/teachers/add': typeof AdminTeachersAddRoute
  '/student/notification/$notificationId': typeof StudentNotificationNotificationIdRoute
  '/teacher/classes/$folderId': typeof TeacherClassesFolderIdRoute
  '/teacher/classes/allCollections': typeof TeacherClassesAllCollectionsRoute
  '/teacher/notifications/$notificationId': typeof TeacherNotificationsNotificationIdRoute
  '/teacher/notifications/add': typeof TeacherNotificationsAddRoute
  '/admin/students': typeof AdminStudentsIndexRoute
  '/admin/teachers': typeof AdminTeachersIndexRoute
  '/student/notification': typeof StudentNotificationIndexRoute
  '/teacher/classes': typeof TeacherClassesIndexRoute
  '/teacher/notifications': typeof TeacherNotificationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/log-in': typeof LogInRoute
  '/sign-up': typeof SignUpRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/settings': typeof StudentSettingsRoute
  '/teacher/calendar': typeof TeacherCalendarRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/admin/students/$studentId': typeof AdminStudentsStudentIdRoute
  '/admin/students/add': typeof AdminStudentsAddRoute
  '/admin/teachers/$teacherId': typeof AdminTeachersTeacherIdRoute
  '/admin/teachers/add': typeof AdminTeachersAddRoute
  '/student/notification/$notificationId': typeof StudentNotificationNotificationIdRoute
  '/teacher/classes/$folderId': typeof TeacherClassesFolderIdRoute
  '/teacher/classes/allCollections': typeof TeacherClassesAllCollectionsRoute
  '/teacher/notifications/$notificationId': typeof TeacherNotificationsNotificationIdRoute
  '/teacher/notifications/add': typeof TeacherNotificationsAddRoute
  '/admin/students': typeof AdminStudentsIndexRoute
  '/admin/teachers': typeof AdminTeachersIndexRoute
  '/student/notification': typeof StudentNotificationIndexRoute
  '/teacher/classes': typeof TeacherClassesIndexRoute
  '/teacher/notifications': typeof TeacherNotificationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/log-in': typeof LogInRoute
  '/sign-up': typeof SignUpRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/settings': typeof StudentSettingsRoute
  '/teacher/calendar': typeof TeacherCalendarRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/admin/students/$studentId': typeof AdminStudentsStudentIdRoute
  '/admin/students/add': typeof AdminStudentsAddRoute
  '/admin/teachers/$teacherId': typeof AdminTeachersTeacherIdRoute
  '/admin/teachers/add': typeof AdminTeachersAddRoute
  '/student/notification/$notificationId': typeof StudentNotificationNotificationIdRoute
  '/teacher/classes/$folderId': typeof TeacherClassesFolderIdRoute
  '/teacher/classes/allCollections': typeof TeacherClassesAllCollectionsRoute
  '/teacher/notifications/$notificationId': typeof TeacherNotificationsNotificationIdRoute
  '/teacher/notifications/add': typeof TeacherNotificationsAddRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/admin/teachers/': typeof AdminTeachersIndexRoute
  '/student/notification/': typeof StudentNotificationIndexRoute
  '/teacher/classes/': typeof TeacherClassesIndexRoute
  '/teacher/notifications/': typeof TeacherNotificationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/log-in'
    | '/sign-up'
    | '/student'
    | '/teacher'
    | '/admin/announcements'
    | '/admin/calendar'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/student/calendar'
    | '/student/courses'
    | '/student/settings'
    | '/teacher/calendar'
    | '/teacher/settings'
    | '/admin/students/$studentId'
    | '/admin/students/add'
    | '/admin/teachers/$teacherId'
    | '/admin/teachers/add'
    | '/student/notification/$notificationId'
    | '/teacher/classes/$folderId'
    | '/teacher/classes/allCollections'
    | '/teacher/notifications/$notificationId'
    | '/teacher/notifications/add'
    | '/admin/students'
    | '/admin/teachers'
    | '/student/notification'
    | '/teacher/classes'
    | '/teacher/notifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/log-in'
    | '/sign-up'
    | '/student'
    | '/teacher'
    | '/admin/announcements'
    | '/admin/calendar'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/student/calendar'
    | '/student/courses'
    | '/student/settings'
    | '/teacher/calendar'
    | '/teacher/settings'
    | '/admin/students/$studentId'
    | '/admin/students/add'
    | '/admin/teachers/$teacherId'
    | '/admin/teachers/add'
    | '/student/notification/$notificationId'
    | '/teacher/classes/$folderId'
    | '/teacher/classes/allCollections'
    | '/teacher/notifications/$notificationId'
    | '/teacher/notifications/add'
    | '/admin/students'
    | '/admin/teachers'
    | '/student/notification'
    | '/teacher/classes'
    | '/teacher/notifications'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/log-in'
    | '/sign-up'
    | '/student'
    | '/teacher'
    | '/admin/announcements'
    | '/admin/calendar'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/student/calendar'
    | '/student/courses'
    | '/student/settings'
    | '/teacher/calendar'
    | '/teacher/settings'
    | '/admin/students/$studentId'
    | '/admin/students/add'
    | '/admin/teachers/$teacherId'
    | '/admin/teachers/add'
    | '/student/notification/$notificationId'
    | '/teacher/classes/$folderId'
    | '/teacher/classes/allCollections'
    | '/teacher/notifications/$notificationId'
    | '/teacher/notifications/add'
    | '/admin/students/'
    | '/admin/teachers/'
    | '/student/notification/'
    | '/teacher/classes/'
    | '/teacher/notifications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LogInRoute: typeof LogInRoute
  SignUpRoute: typeof SignUpRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-in': {
      id: '/log-in'
      path: '/log-in'
      fullPath: '/log-in'
      preLoaderRoute: typeof LogInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/settings': {
      id: '/teacher/settings'
      path: '/settings'
      fullPath: '/teacher/settings'
      preLoaderRoute: typeof TeacherSettingsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/calendar': {
      id: '/teacher/calendar'
      path: '/calendar'
      fullPath: '/teacher/calendar'
      preLoaderRoute: typeof TeacherCalendarRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/settings': {
      id: '/student/settings'
      path: '/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof StudentSettingsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/calendar': {
      id: '/student/calendar'
      path: '/calendar'
      fullPath: '/student/calendar'
      preLoaderRoute: typeof StudentCalendarRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/notifications/': {
      id: '/teacher/notifications/'
      path: '/notifications'
      fullPath: '/teacher/notifications'
      preLoaderRoute: typeof TeacherNotificationsIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/classes/': {
      id: '/teacher/classes/'
      path: '/classes'
      fullPath: '/teacher/classes'
      preLoaderRoute: typeof TeacherClassesIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/notification/': {
      id: '/student/notification/'
      path: '/notification'
      fullPath: '/student/notification'
      preLoaderRoute: typeof StudentNotificationIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/teachers/': {
      id: '/admin/teachers/'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students/': {
      id: '/admin/students/'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/notifications/add': {
      id: '/teacher/notifications/add'
      path: '/notifications/add'
      fullPath: '/teacher/notifications/add'
      preLoaderRoute: typeof TeacherNotificationsAddRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/notifications/$notificationId': {
      id: '/teacher/notifications/$notificationId'
      path: '/notifications/$notificationId'
      fullPath: '/teacher/notifications/$notificationId'
      preLoaderRoute: typeof TeacherNotificationsNotificationIdRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/classes/allCollections': {
      id: '/teacher/classes/allCollections'
      path: '/classes/allCollections'
      fullPath: '/teacher/classes/allCollections'
      preLoaderRoute: typeof TeacherClassesAllCollectionsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/classes/$folderId': {
      id: '/teacher/classes/$folderId'
      path: '/classes/$folderId'
      fullPath: '/teacher/classes/$folderId'
      preLoaderRoute: typeof TeacherClassesFolderIdRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/notification/$notificationId': {
      id: '/student/notification/$notificationId'
      path: '/notification/$notificationId'
      fullPath: '/student/notification/$notificationId'
      preLoaderRoute: typeof StudentNotificationNotificationIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/teachers/add': {
      id: '/admin/teachers/add'
      path: '/teachers/add'
      fullPath: '/admin/teachers/add'
      preLoaderRoute: typeof AdminTeachersAddRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers/$teacherId': {
      id: '/admin/teachers/$teacherId'
      path: '/teachers/$teacherId'
      fullPath: '/admin/teachers/$teacherId'
      preLoaderRoute: typeof AdminTeachersTeacherIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students/add': {
      id: '/admin/students/add'
      path: '/students/add'
      fullPath: '/admin/students/add'
      preLoaderRoute: typeof AdminStudentsAddRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students/$studentId': {
      id: '/admin/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/admin/students/$studentId'
      preLoaderRoute: typeof AdminStudentsStudentIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsStudentIdRoute: typeof AdminStudentsStudentIdRoute
  AdminStudentsAddRoute: typeof AdminStudentsAddRoute
  AdminTeachersTeacherIdRoute: typeof AdminTeachersTeacherIdRoute
  AdminTeachersAddRoute: typeof AdminTeachersAddRoute
  AdminStudentsIndexRoute: typeof AdminStudentsIndexRoute
  AdminTeachersIndexRoute: typeof AdminTeachersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsStudentIdRoute: AdminStudentsStudentIdRoute,
  AdminStudentsAddRoute: AdminStudentsAddRoute,
  AdminTeachersTeacherIdRoute: AdminTeachersTeacherIdRoute,
  AdminTeachersAddRoute: AdminTeachersAddRoute,
  AdminStudentsIndexRoute: AdminStudentsIndexRoute,
  AdminTeachersIndexRoute: AdminTeachersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentCalendarRoute: typeof StudentCalendarRoute
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentSettingsRoute: typeof StudentSettingsRoute
  StudentNotificationNotificationIdRoute: typeof StudentNotificationNotificationIdRoute
  StudentNotificationIndexRoute: typeof StudentNotificationIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCalendarRoute: StudentCalendarRoute,
  StudentCoursesRoute: StudentCoursesRoute,
  StudentSettingsRoute: StudentSettingsRoute,
  StudentNotificationNotificationIdRoute:
    StudentNotificationNotificationIdRoute,
  StudentNotificationIndexRoute: StudentNotificationIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherCalendarRoute: typeof TeacherCalendarRoute
  TeacherSettingsRoute: typeof TeacherSettingsRoute
  TeacherClassesFolderIdRoute: typeof TeacherClassesFolderIdRoute
  TeacherClassesAllCollectionsRoute: typeof TeacherClassesAllCollectionsRoute
  TeacherNotificationsNotificationIdRoute: typeof TeacherNotificationsNotificationIdRoute
  TeacherNotificationsAddRoute: typeof TeacherNotificationsAddRoute
  TeacherClassesIndexRoute: typeof TeacherClassesIndexRoute
  TeacherNotificationsIndexRoute: typeof TeacherNotificationsIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherCalendarRoute: TeacherCalendarRoute,
  TeacherSettingsRoute: TeacherSettingsRoute,
  TeacherClassesFolderIdRoute: TeacherClassesFolderIdRoute,
  TeacherClassesAllCollectionsRoute: TeacherClassesAllCollectionsRoute,
  TeacherNotificationsNotificationIdRoute:
    TeacherNotificationsNotificationIdRoute,
  TeacherNotificationsAddRoute: TeacherNotificationsAddRoute,
  TeacherClassesIndexRoute: TeacherClassesIndexRoute,
  TeacherNotificationsIndexRoute: TeacherNotificationsIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LogInRoute: LogInRoute,
  SignUpRoute: SignUpRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
