/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherSettingsRouteImport } from './routes/teacher/settings'
import { Route as TeacherNotificationsRouteImport } from './routes/teacher/notifications'
import { Route as TeacherClassesRouteImport } from './routes/teacher/classes'
import { Route as TeacherCalendarRouteImport } from './routes/teacher/calendar'
import { Route as StudentSettingsRouteImport } from './routes/student/settings'
import { Route as StudentNotificationsRouteImport } from './routes/student/notifications'
import { Route as StudentCoursesRouteImport } from './routes/student/courses'
import { Route as StudentCalendarRouteImport } from './routes/student/calendar'
import { Route as OwnerStudentsRouteImport } from './routes/owner/students'
import { Route as OwnerSettingsRouteImport } from './routes/owner/settings'
import { Route as OwnerPaymentsRouteImport } from './routes/owner/payments'
import { Route as OwnerDashboardRouteImport } from './routes/owner/dashboard'
import { Route as OwnerAnnouncementsRouteImport } from './routes/owner/announcements'
import { Route as _loginLoginPageRouteImport } from './routes/__login/loginPage'
import { Route as OwnerTeachersIndexRouteImport } from './routes/owner/teachers.index'
import { Route as OwnerTeachersAddRouteImport } from './routes/owner/teachers.add'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSettingsRoute = TeacherSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherNotificationsRoute = TeacherNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherClassesRoute = TeacherClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherCalendarRoute = TeacherCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentSettingsRoute = StudentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCalendarRoute = StudentCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => StudentRoute,
} as any)
const OwnerStudentsRoute = OwnerStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerSettingsRoute = OwnerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPaymentsRoute = OwnerPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAnnouncementsRoute = OwnerAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => OwnerRoute,
} as any)
const _loginLoginPageRoute = _loginLoginPageRouteImport.update({
  id: '/__login/loginPage',
  path: '/loginPage',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerTeachersIndexRoute = OwnerTeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerTeachersAddRoute = OwnerTeachersAddRouteImport.update({
  id: '/teachers/add',
  path: '/teachers/add',
  getParentRoute: () => OwnerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/owner': typeof OwnerRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/loginPage': typeof _loginLoginPageRoute
  '/owner/announcements': typeof OwnerAnnouncementsRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/payments': typeof OwnerPaymentsRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/students': typeof OwnerStudentsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/settings': typeof StudentSettingsRoute
  '/teacher/calendar': typeof TeacherCalendarRoute
  '/teacher/classes': typeof TeacherClassesRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/owner/teachers/add': typeof OwnerTeachersAddRoute
  '/owner/teachers': typeof OwnerTeachersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/owner': typeof OwnerRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/loginPage': typeof _loginLoginPageRoute
  '/owner/announcements': typeof OwnerAnnouncementsRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/payments': typeof OwnerPaymentsRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/students': typeof OwnerStudentsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/settings': typeof StudentSettingsRoute
  '/teacher/calendar': typeof TeacherCalendarRoute
  '/teacher/classes': typeof TeacherClassesRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/owner/teachers/add': typeof OwnerTeachersAddRoute
  '/owner/teachers': typeof OwnerTeachersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/owner': typeof OwnerRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/__login/loginPage': typeof _loginLoginPageRoute
  '/owner/announcements': typeof OwnerAnnouncementsRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/payments': typeof OwnerPaymentsRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/students': typeof OwnerStudentsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/settings': typeof StudentSettingsRoute
  '/teacher/calendar': typeof TeacherCalendarRoute
  '/teacher/classes': typeof TeacherClassesRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/owner/teachers/add': typeof OwnerTeachersAddRoute
  '/owner/teachers/': typeof OwnerTeachersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/owner'
    | '/student'
    | '/teacher'
    | '/loginPage'
    | '/owner/announcements'
    | '/owner/dashboard'
    | '/owner/payments'
    | '/owner/settings'
    | '/owner/students'
    | '/student/calendar'
    | '/student/courses'
    | '/student/notifications'
    | '/student/settings'
    | '/teacher/calendar'
    | '/teacher/classes'
    | '/teacher/notifications'
    | '/teacher/settings'
    | '/owner/teachers/add'
    | '/owner/teachers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/owner'
    | '/student'
    | '/teacher'
    | '/loginPage'
    | '/owner/announcements'
    | '/owner/dashboard'
    | '/owner/payments'
    | '/owner/settings'
    | '/owner/students'
    | '/student/calendar'
    | '/student/courses'
    | '/student/notifications'
    | '/student/settings'
    | '/teacher/calendar'
    | '/teacher/classes'
    | '/teacher/notifications'
    | '/teacher/settings'
    | '/owner/teachers/add'
    | '/owner/teachers'
  id:
    | '__root__'
    | '/'
    | '/owner'
    | '/student'
    | '/teacher'
    | '/__login/loginPage'
    | '/owner/announcements'
    | '/owner/dashboard'
    | '/owner/payments'
    | '/owner/settings'
    | '/owner/students'
    | '/student/calendar'
    | '/student/courses'
    | '/student/notifications'
    | '/student/settings'
    | '/teacher/calendar'
    | '/teacher/classes'
    | '/teacher/notifications'
    | '/teacher/settings'
    | '/owner/teachers/add'
    | '/owner/teachers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  _loginLoginPageRoute: typeof _loginLoginPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/settings': {
      id: '/teacher/settings'
      path: '/settings'
      fullPath: '/teacher/settings'
      preLoaderRoute: typeof TeacherSettingsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/notifications': {
      id: '/teacher/notifications'
      path: '/notifications'
      fullPath: '/teacher/notifications'
      preLoaderRoute: typeof TeacherNotificationsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/classes': {
      id: '/teacher/classes'
      path: '/classes'
      fullPath: '/teacher/classes'
      preLoaderRoute: typeof TeacherClassesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/calendar': {
      id: '/teacher/calendar'
      path: '/calendar'
      fullPath: '/teacher/calendar'
      preLoaderRoute: typeof TeacherCalendarRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/settings': {
      id: '/student/settings'
      path: '/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof StudentSettingsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/calendar': {
      id: '/student/calendar'
      path: '/calendar'
      fullPath: '/student/calendar'
      preLoaderRoute: typeof StudentCalendarRouteImport
      parentRoute: typeof StudentRoute
    }
    '/owner/students': {
      id: '/owner/students'
      path: '/students'
      fullPath: '/owner/students'
      preLoaderRoute: typeof OwnerStudentsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/settings': {
      id: '/owner/settings'
      path: '/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof OwnerSettingsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/payments': {
      id: '/owner/payments'
      path: '/payments'
      fullPath: '/owner/payments'
      preLoaderRoute: typeof OwnerPaymentsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/dashboard': {
      id: '/owner/dashboard'
      path: '/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/announcements': {
      id: '/owner/announcements'
      path: '/announcements'
      fullPath: '/owner/announcements'
      preLoaderRoute: typeof OwnerAnnouncementsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/__login/loginPage': {
      id: '/__login/loginPage'
      path: '/loginPage'
      fullPath: '/loginPage'
      preLoaderRoute: typeof _loginLoginPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/teachers/': {
      id: '/owner/teachers/'
      path: '/teachers'
      fullPath: '/owner/teachers'
      preLoaderRoute: typeof OwnerTeachersIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/teachers/add': {
      id: '/owner/teachers/add'
      path: '/teachers/add'
      fullPath: '/owner/teachers/add'
      preLoaderRoute: typeof OwnerTeachersAddRouteImport
      parentRoute: typeof OwnerRoute
    }
  }
}

interface OwnerRouteChildren {
  OwnerAnnouncementsRoute: typeof OwnerAnnouncementsRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  OwnerPaymentsRoute: typeof OwnerPaymentsRoute
  OwnerSettingsRoute: typeof OwnerSettingsRoute
  OwnerStudentsRoute: typeof OwnerStudentsRoute
  OwnerTeachersAddRoute: typeof OwnerTeachersAddRoute
  OwnerTeachersIndexRoute: typeof OwnerTeachersIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerAnnouncementsRoute: OwnerAnnouncementsRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
  OwnerPaymentsRoute: OwnerPaymentsRoute,
  OwnerSettingsRoute: OwnerSettingsRoute,
  OwnerStudentsRoute: OwnerStudentsRoute,
  OwnerTeachersAddRoute: OwnerTeachersAddRoute,
  OwnerTeachersIndexRoute: OwnerTeachersIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

interface StudentRouteChildren {
  StudentCalendarRoute: typeof StudentCalendarRoute
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentSettingsRoute: typeof StudentSettingsRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCalendarRoute: StudentCalendarRoute,
  StudentCoursesRoute: StudentCoursesRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentSettingsRoute: StudentSettingsRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherCalendarRoute: typeof TeacherCalendarRoute
  TeacherClassesRoute: typeof TeacherClassesRoute
  TeacherNotificationsRoute: typeof TeacherNotificationsRoute
  TeacherSettingsRoute: typeof TeacherSettingsRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherCalendarRoute: TeacherCalendarRoute,
  TeacherClassesRoute: TeacherClassesRoute,
  TeacherNotificationsRoute: TeacherNotificationsRoute,
  TeacherSettingsRoute: TeacherSettingsRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OwnerRoute: OwnerRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  _loginLoginPageRoute: _loginLoginPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
